wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1711038944.825061
    t:
      1:
      - 55
      2:
      - 49
      - 51
      - 55
      3:
      - 13
      - 23
      4: 3.10.13
      5: 0.16.3
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
